// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: app/apps/wxapp/api/api.proto

// package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

package api

import (
	api "app/apps/common/api"
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("app/apps/wxapp/api/api.proto", fileDescriptor_0f8808558ef3350a) }

var fileDescriptor_0f8808558ef3350a = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2c, 0x28, 0xd0,
	0x4f, 0x2c, 0x28, 0x28, 0xd6, 0x2f, 0xaf, 0x80, 0x30, 0x33, 0x41, 0x58, 0xaf, 0xa0, 0x28, 0xbf,
	0x24, 0x5f, 0x48, 0x00, 0x2c, 0xa8, 0x57, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0xaa, 0x57, 0x66,
	0x28, 0xa5, 0x9b, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9e, 0x9f,
	0x9e, 0xaf, 0x0f, 0x56, 0x98, 0x54, 0x9a, 0x06, 0xe6, 0x81, 0x39, 0x60, 0x16, 0xc4, 0x00, 0x29,
	0xe9, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x84, 0xaa, 0xd4, 0xdc, 0x82, 0x92, 0x4a, 0xa8, 0xa4,
	0x0c, 0x54, 0x12, 0x6c, 0x67, 0x5e, 0x5e, 0x7e, 0x49, 0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x54,
	0x56, 0x16, 0xee, 0xb2, 0xe4, 0xfc, 0xdc, 0xdc, 0xfc, 0x3c, 0x54, 0xa7, 0x19, 0x95, 0x71, 0x71,
	0x86, 0x57, 0x04, 0x43, 0x1c, 0x26, 0x94, 0xc9, 0xc5, 0xee, 0x9e, 0x5a, 0x12, 0x5a, 0x9c, 0x5a,
	0x24, 0x24, 0xa3, 0x07, 0x51, 0x8e, 0xe4, 0x68, 0x3d, 0x67, 0xb0, 0x48, 0x50, 0x6a, 0xa1, 0x14,
	0x3e, 0xd9, 0x62, 0x25, 0xa5, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0xc9, 0x08, 0x49, 0xe9, 0x97, 0x57,
	0x40, 0x6d, 0x8d, 0x87, 0x2a, 0xd4, 0x4f, 0x4f, 0x2d, 0x29, 0x2d, 0x4e, 0x2d, 0x72, 0x92, 0x3c,
	0xf1, 0x50, 0x8e, 0xe1, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63,
	0x9c, 0xf1, 0x58, 0x8e, 0x21, 0x8a, 0x39, 0xb1, 0x20, 0x33, 0x89, 0x0d, 0xec, 0x32, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x04, 0x7c, 0x71, 0x54, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WxServiceClient is the client API for WxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WxServiceClient interface {
	GetUser(ctx context.Context, in *api.CommonReq, opts ...grpc.CallOption) (*api.CommonRes, error)
}

type wxServiceClient struct {
	cc *grpc.ClientConn
}

func NewWxServiceClient(cc *grpc.ClientConn) WxServiceClient {
	return &wxServiceClient{cc}
}

func (c *wxServiceClient) GetUser(ctx context.Context, in *api.CommonReq, opts ...grpc.CallOption) (*api.CommonRes, error) {
	out := new(api.CommonRes)
	err := c.cc.Invoke(ctx, "/wxapp.service.v1.WxService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WxServiceServer is the server API for WxService service.
type WxServiceServer interface {
	GetUser(context.Context, *api.CommonReq) (*api.CommonRes, error)
}

// UnimplementedWxServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWxServiceServer struct {
}

func (*UnimplementedWxServiceServer) GetUser(ctx context.Context, req *api.CommonReq) (*api.CommonRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterWxServiceServer(s *grpc.Server, srv WxServiceServer) {
	s.RegisterService(&_WxService_serviceDesc, srv)
}

func _WxService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.CommonReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WxServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wxapp.service.v1.WxService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WxServiceServer).GetUser(ctx, req.(*api.CommonReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WxService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wxapp.service.v1.WxService",
	HandlerType: (*WxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _WxService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/apps/wxapp/api/api.proto",
}
