// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: app/apps/wxapp/api/api.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	app/apps/wxapp/api/api.proto
*/
package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)
import common_service_v1 "app/apps/common/api"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathWxServiceGetUser = "/wx/common_service/getuser"

// WxServiceBMServer is the server API for WxService service.
type WxServiceBMServer interface {
	GetUser(ctx context.Context, req *common_service_v1.CommonReq) (resp *common_service_v1.CommonRes, err error)
}

var WxServiceSvc WxServiceBMServer

func wxServiceGetUser(c *bm.Context) {
	p := new(common_service_v1.CommonReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := WxServiceSvc.GetUser(c, p)
	c.JSON(resp, err)
}

// RegisterWxServiceBMServer Register the blademaster route
func RegisterWxServiceBMServer(e *bm.Engine, server WxServiceBMServer) {
	WxServiceSvc = server
	e.GET("/wx/common_service/getuser", wxServiceGetUser)
}
