// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	api.proto
*/
package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathCommonServiceGetUser = "/common_service/getuser"

// CommonServiceBMServer is the server API for CommonService service.
type CommonServiceBMServer interface {
	GetUser(ctx context.Context, req *CommonReq) (resp *CommonRes, err error)
}

var CommonServiceSvc CommonServiceBMServer

func commonServiceGetUser(c *bm.Context) {
	p := new(CommonReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := CommonServiceSvc.GetUser(c, p)
	c.JSON(resp, err)
}

// RegisterCommonServiceBMServer Register the blademaster route
func RegisterCommonServiceBMServer(e *bm.Engine, server CommonServiceBMServer) {
	CommonServiceSvc = server
	e.GET("/common_service/getuser", commonServiceGetUser)
}
